version: "3.7"

services:
  arklet-minter:
    container_name: arklet_minter
    restart: always
    build:
      context: .
      target: prod
      dockerfile: ./Dockerfile
    command: /app/entrypoint.prod.sh
    volumes:
      - ./ark:/app/ark
      - ./arklet:/app/arklet
    env_file:
      - ./docker/env.postgres.prod
      - ./docker/env.minter.prod
    ports:
      - "8001:8001"

  arklet-resolver:
    container_name: arklet_resolver
    restart: always
    build:
      context: .
      target: prod
      dockerfile: ./Dockerfile
    command: /app/entrypoint.prod.sh
    volumes:
      - ./ark:/app/ark
      - ./arklet:/app/arklet
    env_file:
      - ./docker/env.postgres.prod
      - ./docker/env.resolver.prod
    ports:
      - "8000:8000"
