[tool.poetry]
name = "arklet"
version = "0.1.0"
description = "An unassuming ARK minter, binder, and resolver"
authors = ["Alex Dempsey <avdempsey@archive.org>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/internetarchive/arklet"
packages = [
    { include = "ark" },
    { include = "ark_import" },
]

[tool.poetry.dependencies]
python = "^3.8"
Django = ">=3.2"
psycopg2 = { version = "^2.7", optional = true }
sentry-sdk = {version = "^1.5.10", optional = true}
django-environ = {version = "^0.8.1", optional = true}

[tool.poetry.extras]
postgres = ["psycopg2"]
sentry = ["sentry-sdk"]
environ = ["django-environ"]

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pylint = "^2.13.7"
isort = "^5.10.1"
flake8 = "^4.0.1"
pylint-django = "^2.5.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
